### ISSUE TITLE
teach2 reset learned

### ISSUE THREAD

**Issue by carolinebholmes** [ec3bd/AI-HW1#1]
"⋆ Note that if we change a root variable’s value, it may alter the truth value(s) of learned variables
(see Learn command below). You may assume that this command also resets all learned variables to
the value of false (this simplifies the assignment for you a bit)."

Need to make sure all learned variables are being reset to false when root variables are changed

**Comment by ec3bd** [comment]
It should do that correctly now

**Comment by carolinebholmes** [comment]
Should we check the case where a root variable is being "set" to the value it already has and not reset learned variables, or should we just not worry about that?
